# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AppTravelTeamProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppTravelTeamProject
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  # target 'AppTravelTeamProject-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'AppTravelTeamProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AppTravelTeamProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppTravelTeamProject-tvOS

  target 'AppTravelTeamProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
